create                = true
name                  = "advanced-rsa"
algorithm             = "RSA"
rsa_bits              = "3072"
validity_period_hours = "36"
ca_common_name        = "advanced-rsa.com"
organization_name     = "Advanced RSA Inc."
common_name           = "advanced-rsa.com"
dns_names             = ["foo.advanced-rsa.com", "bar.advanced-rsa.com", ]
ip_addresses          = ["127.0.0.1", "0.0.0.0", ]
