create                = true
name                  = "advanced-ecdsa"
algorithm             = "ECDSA"
ecdsa_curve           = "P521"
validity_period_hours = "48"
ca_common_name        = "advanced-ecdsa.com"
organization_name     = "Advanced ECDSA Inc."
common_name           = "advanced-ecdsa.com"
dns_names             = ["foo.advanced-ecdsa.com", "bar.advanced-ecdsa.com", ]
ip_addresses          = ["127.0.0.1", "0.0.0.0", ]
